In [ ]:
import numpy as np

def create_numpy_array(data, dtype=None, order='C'):
    """
    Create a NumPy array from a Python list or tuple.

    Parameters:
    - data : array_like
        The input data to create the array from. This can be a list, tuple, or nested list/tuple for 2D arrays.
    - dtype : data-type, optional
        The desired data-type for the array. If not provided, the data type will be inferred from the input data.
    - order : {'C', 'F'}, optional
        Specify the memory layout of the array. 'C' means row-major (C-style) order, and 'F' means column-major (Fortran-style) order.
        Default is 'C'.

    Returns:
    - numpy.ndarray
        A NumPy array containing the elements from the input data.

    Example:
    >>> create_numpy_array([1, 2, 3, 4, 5])
    array([1, 2, 3, 4, 5])

    >>> create_numpy_array([[1, 2, 3], [4, 5, 6]], dtype=float)
    array([[1., 2., 3.],
           [4., 5., 6.]])
    """
    return np.array(data, dtype=dtype, order=order)

In [ ]:
import numpy as np

def arange_example(start, stop=None, step=1, dtype=None):
    """
    Generate an array with evenly spaced values within a specified range.

    Parameters:
    - start : int or float
        The starting value of the sequence.
    - stop : int or float, optional
        The end value of the sequence. If not specified, the sequence will stop before this value.
    - step : int or float, optional
        The step size between values in the sequence. Default is 1.
    - dtype : data-type, optional
        The desired data-type for the array. If not specified, the data-type is inferred from the input.

    Returns:
    - ndarray
        An array containing the values in the specified range.

    Examples:
    >>> arange_example(5)
    array([0, 1, 2, 3, 4])

    >>> arange_example(2, 10, 2)
    array([2, 4, 6, 8])

    >>> arange_example(0, 1, 0.1)
    array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

    >>> arange_example(1, 5, dtype=float)
    array([1., 2., 3., 4.])
    """
    return np.arange(start, stop, step, dtype)

In [ ]:
import numpy as np

def create_zeros_array(shape, dtype=float, order='C'):
    """
    Create a new array of given shape and type, filled with zeros.

    Parameters:
    shape : int or tuple of ints
        Shape of the new array, e.g., (2, 3) for a 2x3 matrix.
    dtype : data-type, optional
        The desired data-type for the array, default is float.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in row-major (C-style) or column-major (Fortran-style) order.
        Default is 'C'.

    Returns:
    out : ndarray
        Array of zeros with the given shape and dtype.

    Examples:
    >>> create_zeros_array(3)
    array([0., 0., 0.])

    >>> create_zeros_array((2, 3), dtype=int)
    array([[0, 0, 0],
           [0, 0, 0]])
    """
    return np.zeros(shape, dtype=dtype, order=order)

# Example usage:
print(create_zeros_array(3))
print(create_zeros_array((2, 3), dtype=int))

In [ ]:
import numpy as np

def ones(shape, dtype=None, order='C'):
    """
    Return a new array of given shape and type, filled with ones.

    Parameters:
    shape : int or tuple of ints
        Shape of the new array. For example, if shape is (2, 3), the array will have 2 rows and 3 columns.
    dtype : data-type, optional
        The desired data-type for the array. Default is None, which means NumPy will infer the data-type.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in row-major (C-style) or column-major (Fortran-style) order.
        Default is 'C'.

    Returns:
    out : ndarray
        Array of ones with the specified shape and dtype.

    Examples:
    >>> np.ones(5)
    array([1., 1., 1., 1., 1.])
    >>> np.ones((2, 3), dtype=int)
    array([[1, 1, 1],
           [1, 1, 1]])
    >>> np.ones((2, 3), order='F')
    array([[1., 1., 1.],
           [1., 1., 1.]])
    """
    return np.ones(shape, dtype=dtype, order=order)

In [ ]:
def linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0):
    """
    Return evenly spaced numbers over a specified interval.

    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False. In that case, the sequence consists of all but the last of `num + 1` evenly spaced samples, so that `stop` is excluded. Note that the step size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included. Default is True.
    retstep : bool, optional
        If True, return (`samples`, `step`), where `step` is the spacing between samples. Default is False.
    dtype : dtype, optional
        The type of the output array. If `dtype` is not given, the data type is inferred from the other input arguments.
    axis : int, optional
        The axis in the result to store the samples. Relevant only if the input is multi-dimensional. Default is 0.

    Returns
    -------
    samples : ndarray
        There are `num` equally spaced samples in the closed interval `[start, stop]` or the half-open interval `[start, stop)` (depending on whether `endpoint` is True or False).
    step : float, optional
        The spacing between samples. Only returned if `retstep` is True.

    Examples
    --------
    >>> np.linspace(0, 10, num=5)
    array([ 0. ,  2.5,  5. ,  7.5, 10. ])

    >>> np.linspace(0, 10, num=5, retstep=True)
    (array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)

    >>> np.linspace(0, 10, num=5, endpoint=False)
    array([0., 2., 4., 6., 8.])

    >>> np.linspace(0, 10, num=5, dtype=int)
    array([ 0,  2,  5,  7, 10])

    >>> np.linspace(0, 10, num=5, axis=1)
    array([[ 0. ,  2.5,  5. ,  7.5, 10. ]])
    """
    pass

In [ ]:
import numpy as np

def random_array(shape, seed=None):
    """
    Generate an array of random numbers from a uniform distribution.

    Parameters:
    - shape (tuple of ints): The shape of the output array. For example, shape=(2, 3) creates a 2x3 array.
    - seed (int, optional): Seed for the random number generator. Default is None.

    Returns:
    - ndarray: A new array of the specified shape filled with random numbers from a uniform distribution over [0, 1).

    Example:
    >>> random_array((2, 3))
    array([[0.72477417, 0.80670785, 0.57871338],
           [0.69679463, 0.44097953, 0.88575077]])

    Explanation:
    - This function generates a NumPy array with random numbers from a uniform distribution between 0 and 1.
    - The shape parameter specifies the dimensions of the output array. It can be a tuple of integers representing the number of elements along each dimension.
    - The seed parameter, if provided, initializes the random number generator to produce reproducible results. If not provided, the generator uses the current system time as the seed.
    """
    if seed is not None:
        np.random.seed(seed)
    return np.random.rand(*shape)

In [ ]:
import numpy as np

def generate_random_numbers(mean=0, stddev=1, size=None):
    """
    Generate an array of random numbers from a standard normal distribution.

    Parameters:
    - mean (float, optional): Mean (center) of the distribution. Default is 0.
    - stddev (float, optional): Standard deviation (spread or width) of the distribution. Default is 1.
    - size (int or tuple of ints, optional): Output shape. If None (default), a single value is returned.

    Returns:
    - ndarray: Array of random numbers from a standard normal distribution.

    Example:
    >>> generate_random_numbers()  # Generates a single random number
    0.14697704829295228

    >>> generate_random_numbers(mean=10, stddev=2, size=(3, 3))  # Generates a 3x3 array with mean 10 and standard deviation 2
    array([[10.63480688, 10.72223724,  9.82818732],
           [ 8.36247272,  7.64798731, 10.28400884],
           [ 8.86165094,  9.63457499,  8.63248149]])

    >>> generate_random_numbers(size=5)  # Generates an array of 5 random numbers with default mean and standard deviation
    array([-0.43330344, -0.38339071,  0.14790322,  0.58577341,  0.11328536])
    """
    return np.random.randn(mean, stddev, size)

In [ ]:
import numpy as np

def sum_example(array, axis=None, dtype=None, out=None, keepdims=False):
    """
    Compute the sum of array elements over a given axis.

    Parameters:
    -----------
    array : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the sum is computed. The default is to compute the sum of the flattened array.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the elements are summed. If dtype is not specified, it defaults to the dtype of array, unless array has an integer dtype with a precision less than that of the default platform integer. In that case, the default platform integer is used.
    out : ndarray, optional
        Alternative output array in which to place the result. It must have the same shape as the expected output, but the type of the output values will be cast if necessary.
    keepdims : bool, optional
        If this is set to True, the axes which are reduced are left in the result as dimensions with size one. With this option, the result will broadcast correctly against the original array.

    Returns:
    --------
    sum_along_axis : ndarray
        An array with the same shape as array, with the specified axis removed. If out is specified, a reference to out is returned.
    """
    return np.sum(array, axis=axis, dtype=dtype, out=out, keepdims=keepdims)

In [ ]:
import numpy as np

def calculate_mean(array, axis=None, dtype=None, out=None, keepdims=False):
    """
    Calculate the arithmetic mean along the specified axis.

    Parameters:
    -----------
    array : array_like
        Input array containing the elements for which to compute the mean.
    axis : None or int or tuple of ints, optional
        Axis or axes along which to compute the mean. The default is to compute the mean of the flattened array.
    dtype : data-type, optional
        Type to use in computing the mean. If not specified, the data type of the input array is used.
    out : ndarray, optional
        Output array to store the result. Must have the same shape as the expected output. If not provided, a new array is created.
    keepdims : bool, optional
        If True, the axes which are reduced are left in the result as dimensions with size one.
        With this option, the result will broadcast correctly against the input array.

    Returns:
    --------
    mean : ndarray
        An array containing the mean values along the specified axis.

    Examples:
    ---------
    >>> import numpy as np
    >>> data = np.array([[1, 2, 3], [4, 5, 6]])
    >>> calculate_mean(data)
    3.5
    >>> calculate_mean(data, axis=0)
    array([2.5, 3.5, 4.5])
    >>> calculate_mean(data, axis=1)
    array([2., 5.])
    >>> calculate_mean(data, dtype=np.float64)
    3.5
    >>> calculate_mean(data, keepdims=True)
    array([[3.5]])
    """
    return np.mean(array, axis=axis, dtype=dtype, out=out, keepdims=keepdims)

In [ ]:
def max(array, axis=None, keepdims=False):
    """
    Compute the maximum value along the specified axis.

    Parameters:
    -----------
    array : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        Axis or axes along which to operate. By default, flattened input is used.
        If this is a tuple of ints, the maximum is computed over multiple axes,
        instead of a single axis or all the axes as before.
    keepdims : bool, optional
        If True, the axis where the maximum value is found is left in the result
        as a dimension of size one. This will broadcast the result accordingly.

    Returns:
    --------
    out : ndarray or scalar
        Maximum value along the specified axis. If `out` is None, a new array
        containing the result is returned. If `out` is provided, it must have
        a shape that the inputs broadcast to.

    Examples:
    ---------
    >>> import numpy as np
    >>> arr = np.array([[1, 2, 3], [4, 5, 6]])
    >>> np.max(arr)
    6
    >>> np.max(arr, axis=0)
    array([4, 5, 6])
    >>> np.max(arr, axis=1)
    array([3, 6])
    >>> np.max(arr, keepdims=True)
    array([[6]])

    """
    # Implementation of max function
    ...

In [ ]:
import numpy as np

def min_example(arr, axis=None):
    """
    Calculate the minimum value along a given axis of the input array.

    Parameters:
    -----------
    arr : array_like
        Input array.
    axis : None or int or tuple of ints, optional
        Axis or axes along which to operate. By default, flattened input is used.

    Returns:
    --------
    out : ndarray
        New array with the minimum values along the specified axis. If axis is None, the result is a scalar value.

    Example:
    --------
    >>> arr = np.array([[1, 2, 3], [4, 5, 6]])
    >>> np.min(arr)
    1
    >>> np.min(arr, axis=0)
    array([1, 2, 3])
    >>> np.min(arr, axis=1)
    array([1, 4])
    """
    return np.min(arr, axis=axis)

In [ ]:
import numpy as np

def np_argmax_use_cases():
    """
    Use Cases:
    -----------
    1. Finding the index of the maximum value in a 1D array.
    2. Finding the indices of the maximum values along a specific axis in a multi-dimensional array.

    Parameters:
    -----------
    a : array_like
        Input array.
    axis : int, optional
        Axis along which to operate. By default, flattened input is used.

    Returns:
    --------
    index_array : ndarray of ints
        Array of indices into the array. It has the same shape as `a.shape` with the dimension along `axis` removed.

    Explanation:
    ------------
    `np.argmax()` returns the indices of the maximum values along a specified axis in an array.
    If `axis` is not specified, the function returns the index of the flattened array.
    If multiple maximum values are found, the indices corresponding to the first occurrence are returned.
    """

# Example usage:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Finding the index of the maximum value in the flattened array
index_flat = np.argmax(arr)
print("Index of maximum value in flattened array:", index_flat)

# Finding the index of the maximum value along the columns (axis=0)
index_col_max = np.argmax(arr, axis=0)
print("Indices of maximum values along columns:", index_col_max)

# Finding the index of the maximum value along the rows (axis=1)
index_row_max = np.argmax(arr, axis=1)
print("Indices of maximum values along rows:", index_row_max)

In [ ]:
def argmin_use_case(array, axis=None):
    """
    Find the indices of the minimum value along a specified axis.

    Parameters:
    -----------
    array : array_like
        Input array.

    axis : int or None, optional
        Axis along which to operate. By default, flattened input is used.

    Returns:
    --------
    argmin_indices : ndarray of ints
        Indices of the minimum values along the specified axis.
        If axis is None, a scalar is returned.

    Examples:
    ---------
    >>> import numpy as np
    >>> arr = np.array([[4, 2, 6], [1, 5, 3]])
    >>> np.argmin(arr)
    3
    >>> np.argmin(arr, axis=0)
    array([1, 0, 1])
    >>> np.argmin(arr, axis=1)
    array([1, 0])
    """
    pass  # Placeholder for function implementation

In [ ]:
import numpy as np

def reshape_array(array, new_shape):
    """
    Reshape an array into a specified shape.

    Parameters:
    array : array_like
        Input array to be reshaped.
    new_shape : tuple of ints
        The new shape should be compatible with the original shape. If an integer, then the result will be a 1-D array of that length. One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions.

    Returns:
    reshaped_array : ndarray
        Reshaped array. This will be a new view object if possible; otherwise, it will be a copy.

    Examples:
    >>> arr = np.array([[1, 2, 3], [4, 5, 6]])
    >>> reshape_array(arr, (3, 2))
    array([[1, 2],
           [3, 4],
           [5, 6]])

    >>> reshape_array(arr, (6,))
    array([1, 2, 3, 4, 5, 6])

    >>> reshape_array(arr, (3, -1))
    array([[1, 2],
           [3, 4],
           [5, 6]])
    """
    return np.reshape(array, new_shape)

# Test the function
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(reshape_array(arr, (3, 2)))
print(reshape_array(arr, (6,)))
print(reshape_array(arr, (3, -1)))

In [ ]:
def transpose_example(arr):
    """
    Transposes the rows and columns of the input array.

    Parameters:
    arr : array_like
        Input array to be transposed.

    Returns:
    transposed_arr : ndarray
        Transposed array.

    Examples:
    >>> import numpy as np
    >>> arr = np.array([[1, 2, 3], [4, 5, 6]])
    >>> np.transpose(arr)
    array([[1, 4],
           [2, 5],
           [3, 6]])

    Explanation:
    The np.transpose() function rearranges the dimensions of the input array, swapping the rows and columns.
    In this example, the input array has shape (2, 3), and the transposed array has shape (3, 2).
    """
    transposed_arr = np.transpose(arr)
    return transposed_arr

In [ ]:
import numpy as np

def dot_example(arr1, arr2):
    """
    Compute the dot product of two arrays.

    Parameters:
    -----------
    arr1 : array_like
        First input array. It must be a 1-D or 2-D array.
    arr2 : array_like
        Second input array. It must be a 1-D or 2-D array.

    Returns:
    --------
    dot_product : ndarray
        Dot product of `arr1` and `arr2`. If both inputs are 1-D arrays, it returns the inner product;
        if both inputs are 2-D arrays, it returns the matrix multiplication;
        if either input is N-D, it returns a sum product over the last axis of `arr1` and the second-to-last axis of `arr2`.

    Examples:
    ---------
    >>> arr1 = np.array([1, 2, 3])
    >>> arr2 = np.array([4, 5, 6])
    >>> dot_example(arr1, arr2)
    32

    >>> arr3 = np.array([[1, 2], [3, 4]])
    >>> arr4 = np.array([[5, 6], [7, 8]])
    >>> dot_example(arr3, arr4)
    array([[19, 22],
           [43, 50]])
    """
    dot_product = np.dot(arr1, arr2)
    return dot_product

In [ ]:
import numpy as np

def dot_docstring():
    """
    Compute the dot product of two arrays.

    Parameters:
    -----------
    a, b : array_like
        Input arrays. If both `a` and `b` are 1-D arrays, it is inner product
        of vectors. If both are 2-D arrays, it is matrix multiplication. If
        either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
        and using ``np.multiply(a, b)`` or ``a * b`` is preferred.

    Returns:
    --------
    out : ndarray
        Output array. The dot product of `a` and `b`. This is a scalar if both
        `a` and `b` are 1-D arrays.

    Examples:
    ---------
    >>> a = np.array([1, 2, 3])
    >>> b = np.array([4, 5, 6])
    >>> np.dot(a, b)
    32

    >>> A = np.array([[1, 2], [3, 4]])
    >>> B = np.array([[5, 6], [7, 8]])
    >>> np.dot(A, B)
    array([[19, 22],
           [43, 50]])
    """
    pass

# Uncomment the following line to see the docstring
# help(dot_docstring)

In [ ]:
def numpy_random(size=None, low=0, high=None, dtype=float):
    """
    Generate random numbers or arrays.

    Parameters:
    - size : int or tuple of ints, optional
        Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn.
        If size is None (default), a single value is returned if `high` is None, otherwise the tuple ().
    - low : int or float, optional
        Lower boundary of the output interval. All values generated will be greater than or equal to low,
        unless `high` is specified.
    - high : int or float, optional
        Upper boundary of the output interval. All values generated will be less than high.
    - dtype : data-type, optional
        The desired data-type for the array. If not given, the dtype will be inferred from the other input arguments.

    Returns:
    - out : ndarray or scalar
        Drawn samples from the parameterized distribution.

    Example:
    >>> numpy_random(size=(2, 2)) # Generate a 2x2 array of random floats between 0 and 1
    array([[0.5488135 , 0.71518937],
           [0.60276338, 0.54488318]])

    >>> numpy_random(size=10, low=5, high=10) # Generate 10 random integers between 5 and 10
    array([7, 7, 5, 8, 9, 7, 9, 9, 9, 5])
    """
    pass

In [ ]:
def numpy_sort(arr, axis=-1, kind='quicksort', order=None):
    """
    Sort an array.

    Parameters:
    -----------
    arr : array_like
        Input array to be sorted.
    axis : int, optional
        Axis along which to sort. Default is -1, which means the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. Default is 'quicksort'.
        'quicksort': Fastest sorting algorithm but not stable.
        'mergesort': Stable but slower than quicksort for larger arrays.
        'heapsort': Slower than mergesort and not stable.
        'stable': Stable sorting algorithm; slower than others but maintains the order of equal elements.
    order : str or list of str, optional
        If `arr` is a structured array, specify fields to order by. Default is None.

    Returns:
    --------
    sorted_array : ndarray
        Sorted copy of the input array.

    Examples:
    ---------
    >>> import numpy as np
    >>> arr = np.array([3, 1, 2])
    >>> sorted_arr = np.sort(arr)
    >>> print(sorted_arr)
    [1 2 3]

    >>> arr_2d = np.array([[3, 2], [1, 0]])
    >>> sorted_arr_2d = np.sort(arr_2d, axis=0)
    >>> print(sorted_arr_2d)
    [[1 0]
     [3 2]]

    >>> structured_arr = np.array([('John', 25), ('Jane', 30), ('Doe', 20)], dtype=[('name', 'U10'), ('age', int)])
    >>> sorted_structured_arr = np.sort(structured_arr, order='age')
    >>> print(sorted_structured_arr)
    [('Doe', 20) ('John', 25) ('Jane', 30)]
    """
    # Implementation of numpy.sort() function
    return np.sort(arr, axis=axis, kind=kind, order=order)

In [ ]:
def numpy_unique(arr, return_index=False, return_inverse=False, return_counts=False, axis=None):
    """
    Find the unique elements of an array.

    Parameters:
    - arr : array_like
        Input array. If not already 1D, it will be flattened.
    - return_index : bool, optional
        If True, also return the indices of the input array that result in the unique array.
    - return_inverse : bool, optional
        If True, also return the indices of the unique array that can be used to reconstruct the input array.
    - return_counts : bool, optional
        If True, also return the number of times each unique item appears in the input array.
    - axis : int or None, optional
        The axis or axes along which to operate. By default, flattened input is used.

    Returns:
    - unique : ndarray
        The sorted unique values.
    - unique_indices : ndarray, optional
        The indices of the input array that result in the unique array. Returned if `return_index` is True.
    - unique_inverse : ndarray, optional
        The indices of the unique array that can be used to reconstruct the input array. Returned if `return_inverse` is True.
    - unique_counts : ndarray, optional
        The number of times each unique item appears in the input array. Returned if `return_counts` is True.

    Examples:
    >>> import numpy as np
    >>> arr = np.array([1, 2, 3, 1, 2, 4])
    >>> numpy_unique(arr)
    array([1, 2, 3, 4])
    >>> numpy_unique(arr, return_index=True)
    (array([1, 2, 3, 4]), array([0, 1, 2, 5]))
    >>> numpy_unique(arr, return_counts=True)
    (array([1, 2, 3, 4]), array([2, 2, 1, 1]))
    """
    # Implementation of numpy.unique() function
    pass

In [ ]:
def numpy_concatenate(arrays, axis=0):
    """
    Join a sequence of arrays along an existing axis.

    Parameters:
    arrays : sequence of arrays
        Arrays to be joined. They must have the same shape, except in the dimension corresponding to `axis`.
    axis : int, optional
        The axis along which the arrays will be joined. Default is 0.

    Returns:
    ndarray
        The concatenated array.

    Explanation:
    Concatenation refers to joining arrays along a specified axis. The `numpy.concatenate()` function takes a sequence of arrays and joins them along the specified axis. By default, it concatenates along the first axis (axis 0), which means it stacks arrays vertically. However, you can specify a different axis to concatenate arrays horizontally or along a different dimension.

    Example:
    >>> import numpy as np
    >>> a = np.array([[1, 2], [3, 4]])
    >>> b = np.array([[5, 6]])
    >>> np.concatenate((a, b), axis=0)
    array([[1, 2],
           [3, 4],
           [5, 6]])
    >>> np.concatenate((a, b.T), axis=1)
    array([[1, 2, 5],
           [3, 4, 6]])
    """

In [ ]:
import numpy as np

def numpy_stack_example():
    """
    Example usage of numpy.stack() method:

    Use Case:
    Suppose you have multiple arrays and you want to stack them along a new axis to create a new array.
    This can be useful when you want to combine data from different sources or perform operations on
    corresponding elements of multiple arrays.

    Parameters:
    arrays : sequence of array_like
        The arrays to be stacked. They must have the same shape along all but the first axis.
    axis : int, optional
        The axis along which the arrays will be stacked. Default is 0.

    Returns:
    stacked_array : ndarray
        The stacked array. The stacked array has one more dimension than the input arrays.

    Explanation:
    The numpy.stack() function joins a sequence of arrays along a new axis. It takes a sequence of arrays
    as input and stacks them along the specified axis to create a new array. The input arrays must have
    the same shape along all but the first axis. By default, the new axis is added at the beginning (axis=0),
    but you can specify a different axis using the axis parameter.

    Example:
    >>> a = np.array([1, 2, 3])
    >>> b = np.array([4, 5, 6])
    >>> c = np.array([7, 8, 9])
    >>> stacked = np.stack((a, b, c))
    >>> stacked
    array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
    """
    # Example usage
    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])
    c = np.array([7, 8, 9])
    stacked = np.stack((a, b, c))
    return stacked

# Test the function
result = numpy_stack_example()
print(result)

In [ ]:
def numpy_split(ary, indices_or_sections, axis=0):
    """
    Split an array into multiple sub-arrays.

    Parameters:
    ----------
    ary : array_like
        The array to be split. It must be of the type that can be split (e.g., list, NumPy array).

    indices_or_sections : int or 1-D array_like
        If an integer, then `indices_or_sections` is the number of equally-sized sub-arrays to create. If an array of sorted integers, the entries indicate where along the axis the array is split.

    axis : int, optional
        The axis along which to split the array. By default, it's 0 (the first axis).

    Returns:
    -------
    subarrays : list
        A list of sub-arrays, each with the same shape as the input array, split along the specified axis.

    Examples:
    ---------
    >>> import numpy as np
    >>> arr = np.arange(10)
    >>> np.split(arr, 5)
    [array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

    >>> arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
    >>> np.split(arr, [1, 3], axis=1)
    [array([[ 1],
            [ 4],
            [ 7],
            [10]]),
     array([[ 2,  3],
            [ 5,  6],
            [ 8,  9],
            [11, 12]]),
     array([], shape=(4, 0), dtype=int64)]
    """
    pass